In [4]:
import numpy as np
from numpy.linalg import pinv
import matplotlib.pyplot as plt
x = np.array([[0,1,2]]).T
y = np.array([1,2,3])

## I: Linear regression

### 1: Create the design matrix

In [5]:
def design_matrix(x, degree):
    return np.hstack([np.power(x, i) for i in range(degree + 1)])
    

In [6]:
test = design_matrix(x,2)
print(test)

[[1 0 0]
 [1 1 1]
 [1 2 4]]


### 2: Create the training function

In [28]:
def train(x, y, degree):
    X = design_matrix(x, degree)
    theta_opt = pinv(X).dot(y)
    return theta_opt

In [29]:
theta = train(x, y, 2)

In [36]:
def compute_error(theta, degree, x, y):
    X = design_matrix(x, degree)
    y_predict = X.T.dot(theta)
    print(y_predict)
    err = np.subtract(y_predict,y)
    err2 = np.power(err,2)
    return np.mean(err2)

In [38]:
err = compute_error(theta, 2, x, y)
print(err)

[ 2.  1.  1.]
2.0


### 3: Test of the function 
if we try to minimize the train error ==> overfitting, perfect function with d = 30 for this set of datas, but inapropriate for the others sets (test_err: 366141.235941). Therefore we rather try to minimize the error on the validating set. We find d = 13 and a test_err: 0.383701604651. 

## II Linear regression with radial functions

Create the centers and compute sigma

In [57]:
def get_centers_and_sigma(n_centers):
    centers = np.linspace(-1, 1, n_centers)
    sigma = 2 / float(n_centers)
    return centers, sigma
c, s = get_centers_and_sigma(4)

Design the matrix with the given centers and sigma

In [59]:
def design_matrix(x, centers, sigma):
    X = np.hstack([np.exp((-(x - c)**2)/(2*(sigma**2))) for c in centers])
    return np.hstack((np.ones((len(x), 1)), X))

print(design_matrix(x, [0,1], 1/np.sqrt(2)))

[[ 1.          1.          0.36787944]
 [ 1.          0.36787944  1.        ]
 [ 1.          0.01831564  0.36787944]]


Compute the analytical solution: 

In [64]:
def train(x, y, n_center):
    centers, sigma = get_centers_and_sigma(n_center)
    X = design_matrix(x, centers, sigma)
    theta_opt = pinv(X).dot(y)  

    return theta_opt
print(train(x, y, 4))

[ 3.0668276  -0.17395728 -1.0558404  -1.41933333 -0.45310326]


Compute the error:

In [66]:
def compute_error(theta, n_centers, x, y):
    centers, sigma = get_centers_and_sigma(n_centers)
    X = design_matrix(x, centers, sigma)
    y_predict = X.T.dot(theta)
    err = np.subtract(y_predict,y)
    err2 = np.power(err,2)
    return np.mean(err2)

### 3: Test of the function 
n = 40 is the best for training datas, but test err: 181.671826144
n = 9 is the best for validation datas, test_err: 0.337013008241
TODO: save the graphs

## II: Logistic Regression
### Logistic Regression training
#### Gradient descent

In [70]:
def cost(theta, x, y):
    X = map(lambda v: 1/(1 + np.exp(theta.T * v)), x)
    c = np.mean(1/2(X - y)**2)
    return c

In [71]:
print(cost([1,2,3],x,y))

TypeError: unsupported operand type(s) for -: 'map' and 'int'